Bug: Correctly typing and initialising `prior_loops_cache` (#4654)
If an APR proof on disk contains a `loops_cache`, it cannot be executed
further because of a typing error in the style of:
```
...
File "/nix/store/6bi78qgqbnqryswaly3m4rggsqkrj72w-python3.10-kframework-7.1.145/lib/python3.10/site-packages/pyk/proof/reachability.py", line 793, in step_proof                                                                                    
    prior_loops = step.prior_loops_cache[node.id] + (node.id,)                                                                                                                                                                                        
TypeError: can only concatenate list (not "tuple") to list     
```
when initialising `prior_loops_cache` from disk. 

This PR corrects this bug by enforcing the correct types.